# Site
name: "Achmad Gozali"
title: "Blog"
description: "My personal blog, with extraordinary articles from my daily life in the world of technology"
logo: 'assets/images/personal_logo.png'
favicon: 'assets/images/personal_logo.png'
# baseurl: 
google_analytics: 'UA-132799978-2'
disqus: 'demowebsite'
mailchimp-list: 'https://gmail.us20.list-manage.com/subscribe/post?u=1663556afe69ee65ef581bf5f&amp;id=e08ef6ce19'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ichal:
    name: Ichal
    display_name: Ichal    
    avatar: 'assets/images/ichal_avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: achmadg6@gmail.com
    web: #
    twitter: https://twitter.com/gozali_ichal
    description: "A technology enthusiast, passionate with programming, trading and hacking"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
